opal-core-ws/src/main/java/org/obiba/opal/web/security/AuditInterceptor.java
Just adding query params to rest.log.
Useful for troubleshooting or just have extra information in rest.log to be used by some use reporting tool.
=> Adding query params to rest.log requests

opal-core-ws/src/main/java/org/obiba/opal/web/WebContentInterceptor.java, opal-gwt-client/src/main/resources/org/obiba/opal/web/gwt/app/public/index.html
Our customer reported issues with IE clearly related to caching.
This article explains some issues with IE regarding caching https://support.microsoft.com/en-us/kb/234067
This fix will add extra headers and META HTTP-EQUIV values for making sure nothing is cached
=> Prevent IE caching

opal-server/pom.xml, opal-server/src/main/rpm/opal.sh, opal-server/src/main/rpm/scripts/postinstall.sh, opal-server/src/main/rpm/scripts/postrm.sh, opal-server/src/main/rpm/scripts/prerm.sh
- tested package installation via yum (CentOS 6/7, Fedora 21)
- removed java version verification
=> OPAL-1595 - added pre/postrm scripts

opal-core-ws/src/main/java/org/obiba/opal/web/magma/provider/ConversionExceptionMapper.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/table/presenter/AddViewModalPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/Modal.java
This was requested by our customer, to give the user more detail on certain errors, without the need to check the server logs (not available to everybody)
=> More detailed error message

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/CriterionDropdown.java
Our solution for http://jira.obiba.org/jira/browse/OPAL-2692
=> OPAL-2692 fix: Opal UI doesn't seem to support multiple criterias on the same variable

opal-core-ws/src/main/java/org/obiba/opal/web/magma/AbstractValueTableResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/magma/DatasourceResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/magma/support/HibernateDatasourceFactoryDtoParser.java, opal-core-ws/src/main/java/org/obiba/opal/web/magma/support/MimetypesFileExtensionsMap.java, opal-core/src/main/java/org/obiba/opal/core/runtime/jdbc/DataSourceFactoryBean.java, opal-core/src/main/java/org/obiba/opal/core/service/ProjectsServiceImpl.java, opal-fs/src/main/java/org/obiba/opal/fs/impl/DefaultOpalFileSystem.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/derive/helper/DerivedNumericalVariableGenerator.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/derive/helper/NumericalVariableDerivationHelper.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/derive/view/ValueMapEntry.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/presenter/ScriptEditorPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/support/ClientErrorDtos.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/celltable/AttributeColumn.java, opal-r/src/main/java/org/obiba/opal/r/MagmaAssignROperation.java, opal-search/src/main/java/org/obiba/opal/web/search/TableValueSetsSearchResource.java, opal-shell/src/main/java/org/obiba/opal/shell/CommandLines.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/ReportCommand.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/options/CertificateInfo.java, opal-shell/src/main/java/org/obiba/opal/shell/service/impl/quartz/QuartzCommandJob.java, opal-shell/src/main/java/org/obiba/opal/shell/web/ExportCommandOptionsDtoImpl.java, opal-sshd/src/main/java/org/obiba/opal/server/sshd/OpalFileSystemView.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - “ Dead stores should be removed ”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1854
Please let me know if you have any questions.
Ayman Abdelghany.
=> Dead stores should be removed

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/DefaultCriterionDropdown.java
This is our solution to http://jira.obiba.org/jira/browse/OPAL-2690
We added operations:
* In .. values
* Not in .. values
to values criterion builder for Opal GWT client.
=> OPAL-2690 Add support to 'In .. Values' operation for non-categorized text variables in the Opal UI

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/i18n/Translations.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/project/genotypes/ProjectExportVcfFileModalView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/project/genotypes/ProjectExportVcfFileModalView.ui.xml, opal-shell/pom.xml, opal-shell/src/main/java/org/obiba/opal/shell/commands/ExportVCFCommand.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/options/ExportVCFCommandOptions.java, opal-shell/src/main/java/org/obiba/opal/shell/web/ExportVCFCommandOptionsDtoImpl.java
When filter by table is selected:
* participant ID mapping is optional
* always export samples file
* fail if a participant ID cannot be mapped
Use of CSVWriter, CSV header added.
=> OPAL-2919 Filter by table fixed

opal-gwt-client/pom.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/i18n/Translations.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/search/entities/IndexedVariableSuggestOracle.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/search/entities/SearchEntitiesPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/search/entities/SearchEntitiesUiHandlers.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/search/entities/SearchEntitiesView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/search/entities/SearchEntitiesView.ui.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/search/variables/SearchVariablesPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/search/variables/SearchVariablesUiHandlers.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/search/variables/SearchVariablesView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/search/variables/SearchVariablesView.ui.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/search/variables/VariableFieldSuggestOracle.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/CategoricalCriterionDropdown.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/DateTimeCriterionDropdown.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/DefaultCriterionDropdown.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/IdentifiersCriterionDropdown.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/NumericalCriterionDropdown.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/ValueSetCriterionDropdown.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/ValueSetVariableCriterion.java, opal-search/src/main/java/org/obiba/opal/web/search/support/EsResultConverter.java
* update browser history with selected variable criteria
* criterion dropdowns are rebuilt when original query is provided
* variable field and variable criterion suggestions can be searched with multiple words (with negation support)
=> OPAL-2935 Search entities query can be bookmarked

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/VariableSuggestOracle.java
Special characters are described here: https://lucene.apache.org/core/2_9_4/queryparsersyntax.html
=> OPAL-3017 - replace lucene special characters except for braces and "-" characters

opal-core-ws/src/main/java/org/obiba/opal/web/magma/support/PluginDatasourceFactoryDtoParser.java, opal-core-ws/src/main/java/org/obiba/opal/web/project/ProjectTransientDatasourcesResource.java, opal-core-ws/src/test/java/org/obiba/opal/web/magma/DatasourceResourceTest.java, opal-core/src/main/java/org/obiba/opal/core/runtime/PluginsManager.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/i18n/Translations.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/importdata/ImportConfig.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/importdata/ImportModule.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/importdata/presenter/DataImportPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/importdata/presenter/DatasourcePluginFormatStepPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/importdata/view/DataImportView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/importdata/view/DataImportView.ui.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/importdata/view/DatasourcePluginFormatStepView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/importdata/view/DatasourcePluginFormatStepView.ui.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/support/DatasourceDtos.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/support/jsonschema/JsonSchemaGWT.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/DynamicRadioGroup.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/SchemaUiContainer.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/rest/client/UriBuilders.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/CopyCommand.java, opal-spi/src/main/java/org/obiba/opal/spi/datasource/DatasourceService.java, opal-spi/src/main/java/org/obiba/opal/spi/datasource/DatasourceServiceLoader.java, opal-spi/src/main/java/org/obiba/opal/spi/datasource/DatasourceUsage.java, opal-web-model/src/main/protobuf/Magma.proto, opal-ws/src/main/java/org/obiba/opal/web/plugins/OpalDatasourcePluginJsonSchemaResource.java
Still need to do:
- type string format radio component
- type array (of string) component
- type boolean component
as well as their validations
For now the import step is almost complete, the job submission is one of the steps left, then a better validation and better feedback for errors. Currently only gives the name/title of the field in error.
=> Datasource spi

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/importdata/view/DatasourcePluginFormatStepView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/DynamicRadioGroup.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/SchemaUiContainer.java
Also make sure containerPanel is clear before building widgets.
=> Add support for format radio

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/support/jsonschema/JsonSchemaGWT.java, opal-spi/src/main/java/org/obiba/opal/spi/datasource/AbstractDatasourceService.java
This way the order of schemas may be ensured
=> Manage root schemas of type array

opal-core-api/src/main/java/org/obiba/opal/core/domain/OpalAnalysis.java, opal-core-ws/src/main/java/org/obiba/opal/web/project/Dtos.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/AnalyseCommand.java, opal-spi-r/src/main/java/org/obiba/opal/spi/r/analysis/RAnalysis.java, opal-spi/src/main/java/org/obiba/opal/spi/analysis/AbstractAnalysis.java, opal-spi/src/main/java/org/obiba/opal/spi/analysis/Analysis.java
Changed getVariables() type to string as we only need variable names.
=> Saved variables in OrientDB.

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/GwtApp.gwt.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/AnalysesPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/AnalysesUiHandlers.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/AnalysesView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/AnalysesView.ui.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/AnalysisModule.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/i18n/Translations.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/MagmaModule.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/presenter/TablePresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/presenter/TableUiHandlers.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/view/TableView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/view/TableView.ui.xml
missing:
- action handlers for all different actions (run, view, duplicate, delete)
- hide / show tab depending on permissions and / or presence of plugin
- modal to create / edit / view analysis
The result metrics (count, status, date) seem as though they should be based on the last result. Is that the case? Is the count supposed to represent the number of sub result in that case?
=> Initial UI representation

opal-core-ws/src/main/java/org/obiba/opal/web/analysis/TableAnalysisResource.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/component/ResultsPanel.java
Filtering by date as is. Should a date format be applied or should the filter be done on another field?
=> download shouldn't delete result, filter is reset on delete

opal-core-api/src/main/java/org/obiba/opal/core/domain/OpalAnalysisResult.java, opal-core-api/src/main/java/org/obiba/opal/core/service/AnalysisExportService.java, opal-core-api/src/main/java/org/obiba/opal/core/service/NoSuchAnalysisException.java, opal-core-api/src/main/java/org/obiba/opal/core/service/OpalAnalysisResultService.java, opal-core-ws/src/main/java/org/obiba/opal/web/analysis/NoSuchAnalysisExceptionMapper.java, opal-core-ws/src/main/java/org/obiba/opal/web/analysis/TableAnalysisResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/project/Dtos.java, opal-core/src/main/java/org/obiba/opal/core/service/AnalysisExportServiceImpl.java, opal-core/src/main/java/org/obiba/opal/core/service/OpalAnalysisResultServiceImpl.java, opal-core/src/main/java/org/obiba/opal/core/service/OpalAnalysisServiceImpl.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/AnalysesView.ui.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/AnalysisModalView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/component/AnalysisPanel.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/component/AnalysisPanel.ui.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/analysis/component/ResultsPanel.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/i18n/Translations.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/AnalyseCommand.java, opal-spi/src/main/java/org/obiba/opal/spi/analysis/AbstractAnalysisResult.java, opal-spi/src/main/java/org/obiba/opal/spi/analysis/AnalysisResult.java, opal-web-model/src/main/protobuf/Projects.proto
=> Changed analysisId to analysisName, name validation, fixed var chooser bug.

opal-core-ws/src/main/java/org/obiba/opal/web/magma/AbstractValueTableResource.java, opal-core/src/main/java/org/obiba/opal/core/service/DefaultIdentifiersTableService.java, opal-search/src/main/java/org/obiba/opal/search/service/OpalSearchService.java
=> Entities paging

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/i18n/Translations.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/datasource/presenter/RestoreViewsModalPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/datasource/view/RestoreViewsModalView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/event/ViewsRestoreSubmittedEvent.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/presenter/DatasourcePresenter.java
=> refresh when all restores are done

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/view/DatasourceView.java
=> hide backup views button when no views on render

opal-core-api/src/main/java/org/obiba/opal/core/event/OpalGeneralConfigUpdatedEvent.java, opal-core/src/main/java/org/obiba/opal/core/service/OpalGeneralConfigServiceImpl.java, opal-core/src/test/java/org/obiba/opal/core/service/OpalGeneralConfigServiceImplTest.java, opal-httpd/src/main/java/org/obiba/opal/server/httpd/OpalCallbackFilter.java, opal-httpd/src/main/java/org/obiba/opal/server/httpd/OpalLoginFilter.java
=> Update the Opal public URL in filters.

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/administration/idproviders/edit/IDProviderView.java
=> Clear groups and groupsClaim when empty.

opal-core-ws/src/main/java/org/obiba/opal/web/FilesResource.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/fs/FileSystemModule.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/fs/event/UnzipRequest.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/fs/presenter/FileExplorerPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/fs/presenter/FileExplorerUiHandlers.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/fs/presenter/UnzipModalPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/fs/presenter/UnzipModalUiHandlers.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/fs/view/FileExplorerView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/fs/view/FileExplorerView.ui.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/fs/view/UnzipModalView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/fs/view/UnzipModalView.ui.xml, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/i18n/Translations.java
=> unzip zip archive

opal-ui/src/components/CommandStates.vue, opal-ui/src/components/datasource/AddToViewDialog.vue, opal-ui/src/components/datasource/AddViewDialog.vue, opal-ui/src/components/datasource/CategoriesRangeDialog.vue, opal-ui/src/components/datasource/CategoryDialog.vue, opal-ui/src/components/datasource/DatasourceTables.vue, opal-ui/src/components/datasource/EditTableDialog.vue, opal-ui/src/components/datasource/EditVariableDialog.vue, opal-ui/src/components/datasource/TableValues.vue, opal-ui/src/components/datasource/TableVariables.vue, opal-ui/src/components/datasource/VariableAttributes.vue, opal-ui/src/components/datasource/VariableCategories.vue, opal-ui/src/components/datasource/VariableScript.vue, opal-ui/src/components/datasource/VariableSummary.vue, opal-ui/src/components/permissions/AccessControlList.vue, opal-ui/src/i18n/en/index.js, opal-ui/src/i18n/fr/index.js, opal-ui/src/pages/ProjectTablePage.vue, opal-ui/src/pages/ProjectVariablePage.vue, opal-ui/src/stores/datasource.ts
=> feat(ui): add variables to a view and  other variable edition acitons

opal-ui/src/components/admin/profiles/ProfileAclsList.vue, opal-ui/src/components/admin/profiles/ProfilesList.vue, opal-ui/src/components/permissions/AccessControlTable.vue, opal-ui/src/i18n/en/index.js, opal-ui/src/i18n/fr/index.js, opal-ui/src/pages/AdminTaxonomiesPage.vue, opal-ui/src/pages/AdminTaxonomyPage.vue, opal-ui/src/pages/AdminTaxonomyVocabularyPage.vue, opal-ui/src/pages/ProjectPermsPage.vue, opal-ui/src/stores/projects.ts, opal-ui/src/utils/authz.ts
=> Added project permissions page

opal-ui/.eslintrc-auto-import.json, opal-ui/package-lock.json, opal-ui/src/auto-imports.d.ts, opal-ui/src/boot/api.ts, opal-ui/src/components/FieldsList.vue, opal-ui/src/components/SchemaForm.vue, opal-ui/src/components/SchemaFormItem.vue, opal-ui/src/components/admin/taxonomies/ImportTaxonomyFileDialog.vue, opal-ui/src/components/models.ts, opal-ui/src/components/resources/ResourceReference.vue, opal-ui/src/components/resources/ResourceReferenceDialog.vue, opal-ui/src/components/resources/ResourceReferences.vue, opal-ui/src/css/app.scss, opal-ui/src/i18n/en/index.js, opal-ui/src/i18n/fr/index.js, opal-ui/src/layouts/MainLayout.vue, opal-ui/src/pages/ProjectPage.vue, opal-ui/src/pages/ProjectResourcePage.vue, opal-ui/src/pages/ProjectResourcesPage.vue, opal-ui/src/pages/ProjectTablePage.vue, opal-ui/src/pages/ProjectTablesPage.vue, opal-ui/src/pages/ProjectVariablePage.vue, opal-ui/src/pages/SigninPage.vue, opal-ui/src/router/routes.ts, opal-ui/src/stores/datasource.ts, opal-ui/src/stores/resources.ts, opal-ui/src/stores/taxonomies.ts
List, add, remove, edit, duplicate resources.
=> feat(ui): Resources

opal-core-ws/src/main/java/org/obiba/opal/web/magma/DroppableTableResourceImpl.java, opal-ui/src/components/resources/AddResourceViewDialog.vue, opal-ui/src/i18n/en/index.js, opal-ui/src/i18n/fr/index.js, opal-ui/src/pages/ProjectResourcePage.vue, opal-ui/src/pages/ProjectTablePage.vue, opal-ui/src/stores/datasource.ts
=> feat: resource views creation, display and deletion

opal-ui/src/components/datasource/ScriptDialog.vue, opal-ui/src/components/datasource/VariableScript.vue, opal-ui/src/components/datasource/VariableScriptDialog.vue, opal-ui/src/components/datasource/ViewWhereScript.vue, opal-ui/src/i18n/en/index.js, opal-ui/src/i18n/fr/index.js, opal-ui/src/pages/ProjectTablePage.vue, opal-ui/src/stores/datasource.ts, opal-web-model/src/main/java/org/obiba/opal/web/magma/Dtos.java
=> feat: edit where script of views #3838

opal-search/src/main/java/org/obiba/opal/search/service/impl/AnalyzerFactory.java, opal-search/src/main/java/org/obiba/opal/search/service/impl/VariablesAnalyzer.java, opal-search/src/main/java/org/obiba/opal/search/service/impl/VariablesAnalyzerFactory.java, opal-search/src/main/java/org/obiba/opal/search/service/impl/VariablesIndexImpl.java, opal-search/src/main/java/org/obiba/opal/search/service/impl/VariablesIndexManagerImpl.java, opal-search/src/main/java/org/obiba/opal/search/service/impl/VariablesQueryExecutor.java, opal-ui/src/layouts/MainLayout.vue
Find term in variable names (3 chars)
=> feat: n-gram analyzer added

opal-core/src/main/java/org/obiba/opal/core/service/LocalOrientDbServerFactory.java, opal-server/src/main/java/org/obiba/opal/server/OpalServer.java, opal-ui/src/pages/SearchPage.vue, opal-upgrade/src/main/java/org/obiba/opal/core/upgrade/v5_0_x/EhCacheFolderUpgradeStep.java, opal-upgrade/src/main/java/org/obiba/opal/core/upgrade/v5_0_x/ElasticSearchUpgradeStep.java, opal-upgrade/src/main/resources/upgrade-context.xml
Delete folders:
* OrientDB: OSystem will be recreated by OrientDB
* EhCache: summaries no longer in EhCache
* Search ES: deprecated plugin
=> feat: upgrade to opal 5.0 #3907

opal-ui/src/components/admin/databases/EditDatabaseDialog.vue, opal-ui/src/i18n/en/index.js, opal-ui/src/i18n/fr/index.js, opal-ui/src/stores/system.ts
=> Fixed the driver <=> url change bug

opal-core-api/src/main/java/org/obiba/opal/core/domain/security/SubjectProfile.java, opal-core-api/src/main/java/org/obiba/opal/core/service/SubjectProfileService.java, opal-core-ws/src/main/java/org/obiba/opal/web/security/AuthenticationExecutorImpl.java, opal-core/src/main/java/org/obiba/opal/core/service/SubjectProfileServiceImpl.java
Make it permanent when validated.
=> feat: set a tmp secret when 2FA is enforced

opal-ui/src/components/ProjectDrawer.vue, opal-ui/src/components/project/AddProjectDialog.vue
=> Corrected conditions to hide/show VCF based on permission and plugin availability

opal-ui/src/components/files/FileView.vue, opal-ui/src/i18n/en/index.js, opal-ui/src/i18n/fr/index.js
=> Added download pwd encryption length validation

opal-shell/src/main/java/org/obiba/opal/shell/commands/CopyCommand.java
=> Decode VFS file path before any folder creation

opal-search/src/main/java/org/obiba/opal/search/AbstractSearchUtility.java, opal-search/src/main/java/org/obiba/opal/search/service/QuerySettings.java, opal-search/src/main/java/org/obiba/opal/search/service/impl/ContentQueryExecutor.java, opal-search/src/main/java/org/obiba/opal/search/service/support/ScoreDocSerializer.java, opal-search/src/main/java/org/obiba/opal/web/search/DatasourcesVariablesSearchResource.java, opal-search/src/main/java/org/obiba/opal/web/search/TableVariablesSearchResource.java, opal-ui/src/pages/SearchVariablesPage.vue, opal-ui/src/stores/search.ts, opal-web-model/src/main/protobuf/Search.proto
=> Clear only when starting search, added lastDoc for pagination

opal-ui/src/components/datasource/VariableCategories.vue, opal-ui/src/components/datasource/VariableSummary.vue
=> Fixed some TS warning and fullIfCached

opal-core-ws/src/main/java/org/obiba/opal/web/FilesResource.java, opal-core/src/main/resources/META-INF/defaults.properties
Check allowed/denied file extensions on file upload and file rename/move
=> feat: added white and black list of file extensions

opal-ui/package-lock.json, opal-ui/package.json, opal-ui/quasar.extensions.json, opal-ui/src/components/charts/VuePlotly.vue, opal-ui/src/components/datasource/VariableAttributes.vue, opal-ui/src/components/files/FileSelect.vue, opal-ui/src/components/taxonomies/TaxonomyEntityContent.ts, opal-ui/src/plotly.d.ts, opal-ui/src/utils/notify.ts, opal-ui/src/utils/plugins.ts
TODO: Reset sort in taxonomy page is not working the 1st time...
=> Fixed some issues related to Vite 2.0

opal-ui/src/components/project/AddProjectDialog.vue
=> User home as initial and load existing export folder

opal-ui/src/components/SchemaFormItem.vue
=> Made sure the modelValue is properly updated

opal-core-ws/src/main/java/org/obiba/opal/web/project/ProjectResource.java, opal-ui/src/components/ProjectDrawer.vue, opal-ui/src/pages/ProjectGenoTypesPage.vue, opal-ui/src/pages/ProjectPage.vue, opal-ui/src/stores/projects.ts
=> Add permissions checks
