obiba/opal

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/magma/presenter/ValuesTablePresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/celltable/ValueRenderer.java
In Opal GWT, table values tab, when we define 'number of visible variables' bigger than 5 (15 lets say), the table will have drawing errors and be incomplete not displaying the rightmost variable values.
This is happening for 2 reasons: 
* currentVariablesFilterSelect was not being properly updated in ValuesTablePresenter.DataFetcherImpl. request
* ValueRenderer.getValue was not 'NullPointerException' safe
This solves that problem
=> bugfix Values tab, visible variables glitch

opal-shell/src/main/java/org/obiba/opal/shell/commands/ImportCommand.java
The stacktraces are now included in the task log, drilling down in all the exception causes.
Its very common to observe the innermost exception to be 'caused' by itself, and so causing endless loops for the unaware. So we only recurse in the cause if its different from the container exception
=> Improvement: Stacktraces are now included in task log

opal-gwt-client/src/main/resources/org/obiba/opal/web/gwt/app/public/undefined.cache.js
Our customer requested a clear message in Opal webapp when they use a browser that is not supported. 
Moreover, one of the sites reported that IE 11 was not wortking. That happened because something on that configuration was preventing GWT from getting the user.agent, and so Opal didn't work in that site.
Anyway, in both cases the browser is not considered supported and gets this message, which was the customer intent
=> Improvement: Unrecognized/Unsupported browser now shows an alert with clear message

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/GwtApp.gwt.xml, opal-gwt-client/src/main/resources/org/obiba/opal/web/gwt/app/public/undefined.cache.js
Opal doesn't work with IE8 (some javascript error)
Given this and the age of this browser, we removed support for it.
Its no longer a permutation for GWT and was removed from the list of supported browsers in the alert.
=> Removing support for IE8 on GWT permutations and warning dialog

opal-server/pom.xml, opal-server/src/main/rpm/scripts/postinstall.sh, opal-server/src/main/rpm/scripts/postrm.sh, opal-server/src/main/rpm/scripts/preinstall.sh, opal-server/src/main/rpm/scripts/prerm.sh
This patch requires that the old installed packages be removed as follows:
/etc/init.d/rserver stop
rpm -e rserver-admin-<version> --noscripts  # no data files will be removed
=> OPAL-2786 - fixed install and remove scripts

opal-core/src/main/java/org/obiba/opal/core/service/QuartzTablesCreator.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/administration/identifiers/presenter/IdentifiersTablePresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/administration/identifiers/view/GenerateIdentifiersModalView.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/project/admin/ProjectAdministrationPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/ui/DiffTable.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2131 - “Primitives should not be boxed just for "String" conversion”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2131
Please let me know if you have any questions.
Ayman Abdelghany.
=>  Primitives should not be boxed just for "String" conversion

opal-config-migrator/src/main/java/org/obiba/opal/tools/LegacyOrientDbExporter.java, opal-core/src/main/java/org/obiba/opal/core/tools/OrientDbUtil.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/support/PlaceRequestHelper.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/support/ValueRenderingHelper.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - “Utility classes should not have public constructors ”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
Ayman Abdelghany.
=>  Utility classes should not have public constructors

opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/administration/identifiers/presenter/ImportIdentifiersMappingModalPresenter.java, opal-r/src/main/java/org/obiba/opal/r/MagmaAssignROperation.java, opal-r/src/main/java/org/obiba/opal/r/StringAssignROperation.java, opal-reporting/src/main/java/org/obiba/opal/reporting/service/r/RReportServiceImpl.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/CopyCommand.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1149 - “Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used ”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1149
Please let me know if you have any questions.
Ayman Abdelghany.
=> Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used

opal-core-ws/src/main/java/org/obiba/opal/web/vcf/VCFStoreResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/vcf/VCFStoreResourceImpl.java, opal-shell/src/main/java/org/obiba/opal/shell/CommandJob.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/ExportVCFCommand.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/ImportVCFCommand.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/options/ExportVCFCommandOptions.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/options/ImportVCFCommandOptions.java, opal-shell/src/main/java/org/obiba/opal/shell/web/ExportVCFCommandOptionsDtoImpl.java, opal-shell/src/main/java/org/obiba/opal/shell/web/ImportVCFCommandOptionsDtoImpl.java, opal-shell/src/main/java/org/obiba/opal/shell/web/WebShellCommandRegistry.java, opal-shell/src/main/java/org/obiba/opal/web/shell/ProjectCommandsResource.java, opal-web-model/src/main/protobuf/Commands.proto
Direct import and download is not possible any more. This allows to handle long running tasks and  simplifies the file download code (encryption).
=> OPAL-2875 Commands for import/export of VCF files added

opal-core-api/src/main/java/org/obiba/opal/core/service/VCFSamplesMappingService.java, opal-core/src/main/java/org/obiba/opal/core/service/VCFSamplesMappingServiceImpl.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/project/genotypes/ProjectExportVcfFileModalView.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/ExportVCFCommand.java, opal-spi/src/main/java/org/obiba/opal/spi/vcf/VCFStore.java
Reverts obiba/opal#769 because you were not supposed to overload the VCF store API: just pass the appropriate list of samples.
=> Revert "OPAL-2866 - export check if a filtering table is selected or control …"

opal-core/src/main/java/org/obiba/opal/core/service/ProjectsServiceImpl.java
orientdb's transaction type is currently set to optimistic, meaning there is not much checks for other transactions or locks. The only other options are "no transaction" or a pessimistic transaction. The latter is not yet supported (version 2.2.x, we are on 2.1.x).
We can either do this change for only projects or do a general change and make the orientdb service's save method synchronized.
=> OPAL-2888 - enclose a project's orientdb save in a synchronized block

opal-core-ws/src/main/java/org/obiba/opal/web/project/ProjectResource.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/project/admin/ProjectAdministrationPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/project/genotypes/ProjectGenotypesPresenter.java, opal-gwt-client/src/main/java/org/obiba/opal/web/gwt/app/client/project/view/ProjectPresenter.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/ImportVCFCommand.java, opal-web-model/src/main/java/org/obiba/opal/web/plugins/Dtos.java, opal-ws/src/main/java/org/obiba/opal/web/services/PluginsResource.java
A call to /plugins should no longer set the "custom" properties.
I also removed the "auto add vcf store service" to a project because the authorizer seems to add a vcf-store automatically and this change is not reflected in the UI.
Another change for this would be to refresh the project on every tab.
=> OPAL-2914 - show vcf store section in a project's administration page

pom.xml
Jsr305 annotation dependency is still at 2.0.3, newest version is 3.0.2 (March 2017).
=> Updated findbugs maven plugin dependency version to 3.0.4

opal-core-api/src/main/java/org/obiba/opal/core/domain/OpalAnalysis.java, opal-core-api/src/main/java/org/obiba/opal/core/service/OpalAnalysisService.java, opal-core-ws/src/main/java/org/obiba/opal/web/AnalysisResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/magma/TableResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/magma/TableResourceImpl.java, opal-core-ws/src/main/java/org/obiba/opal/web/project/ProjectResource.java, opal-core/src/main/java/org/obiba/opal/core/service/OpalAnalysisResultServiceImpl.java, opal-core/src/main/java/org/obiba/opal/core/service/OpalAnalysisServiceImpl.java, opal-shell/src/main/java/org/obiba/opal/shell/commands/AnalyseCommand.java
Reverts obiba/opal#3347 because the resources must return DTOs instead of hard-coded JSON strings. DTOs are handled by protobuf and can in binary format (non JSON).
=> Revert "Feature/table analysis resource"

opal-server/src/main/deb/debian/postinst
This bug appears if `opal-server` and `opal-search-es` plugin are both installed in `/usr/share/`. The new installation's soft-linking of `opal` will fail.
=> Bugfix for a better and more secure soft linking of Opal folder

opal-server/src/main/rpm/opal.default, opal-server/src/main/rpm/opal.service
I had issues starting Opal after the change to systemd. It turns out the variable was the problem. I made some changes local in my system and now it works for me. As I am no expert at this topic please review.
=> Fix for RPM in CentOS

opal-core-ws/src/main/java/org/obiba/opal/web/BaseResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/magma/AbstractValueTableResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/magma/ValueSetsResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/project/ProjectResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/project/ProjectsResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/project/resource/ProjectResourceReferenceResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/project/resource/ProjectResourceReferencesResource.java, opal-core-ws/src/main/java/org/obiba/opal/web/security/AbstractPermissionsResource.java, opal-shell/src/main/java/org/obiba/opal/web/shell/AbstractCommandsResource.java, opal-shell/src/main/java/org/obiba/opal/web/shell/ProjectCommandsResource.java, opal-shell/src/main/java/org/obiba/opal/web/shell/RClusterCommandsResource.java
The reason is that `@Transactional` and an interface with a `default` implementation causes an error, for example `@GET` endpint was reported to be not part of the resource!
Possible explanation: *When you use the `@Transactional` annotation, it typically creates a proxy around the object to manage transactions. However, default methods in interfaces don't work seamlessly with this proxy mechanism.*
> There are still issues with OPTIONS compared to the older version.  For example `/datasource/CLS/table/Wave1/variables` still only returns OPTIONS!
=> Converted BaseResource to an abstract class

opal-core/src/main/resources/META-INF/defaults.properties, opal-core/src/main/resources/spring/opal-core/email.xml
Hi,
In some scenarios, the email sending service requires a secure connection.
After trying several ways to modify the Opal configuration file (opal-config.properties) or pass JAVA_OPTS arguments, the only way I found to make the email work with SSL was by applying these modifications.
Thanks!
=> Adds smtp security params

opal-ui/src/components/files/FileSelect.vue, opal-ui/src/components/files/FileView.vue, opal-ui/src/i18n/en/index.js, opal-ui/src/i18n/fr/index.js, opal-ui/src/utils/strings.ts
Fixes: #3951 and #3951
- Added a search bar in FileSelect and FileView.
- Removed `..` that was confusing many people. Breadcrumb is the way to go back up the hierarchy as in the old Opal and many file browsers.
=> Cleanup selections when confirmation is cancelled, added search bar

opal-r/src/main/java/org/obiba/opal/r/datasource/RAssignDatasource.java, opal-r/src/main/java/org/obiba/opal/r/magma/util/DateRange.java, opal-r/src/main/java/org/obiba/opal/r/magma/util/DateTimeRange.java, opal-r/src/main/java/org/obiba/opal/r/magma/util/DoubleRange.java, opal-r/src/main/java/org/obiba/opal/r/magma/util/IntegerRange.java, opal-r/src/main/java/org/obiba/opal/r/magma/util/NumberRange.java, opal-r/src/main/java/org/obiba/opal/r/magma/util/Range.java, opal-r/src/test/java/org/obiba/opal/r/magma/VectorTypeTest.java
Previously: a date or datetime variable was downgraded to text when assigned to R because Date and Posixct objects cannot be labelled. 
Now: the the original data type is kept, the R column is not labelled and instead `na_values` and `na_range` attributes are added. 
Limitations: these `na_values` and `na_range` attributes could be potentially used when `haven` writes to SPSS, but it is not the case because of a limited sav format support from haven.
=> fix: keep original data type when exporting temporal variables with categories 
